# Generated by Django 3.2.14 on 2022-09-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipa_na_mpesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True, unique=True)),
                ('MerchantRequestID', models.CharField(max_length=30, null=True, unique=True)),
                ('ResultCode', models.IntegerField(null=True)),
                ('ResultDesc', models.TextField(max_length=200, null=True)),
                ('Amount', models.FloatField(null=True)),
                ('MpesaReceiptNumber', models.CharField(max_length=50, null=True, unique=True)),
                ('Balance', models.CharField(blank=True, max_length=10, null=True)),
                ('TransationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('state', django_fsm.FSMField(default='initiated', max_length=50, protected=True)),
            ],
            options={
                'verbose_name': 'Lipa Na Mpesa Payment',
                'verbose_name_plural': 'Lipa Na Mpesa Payments',
                'ordering': ['-TransationDate'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, null=True, unique=True)),
                ('mode', models.CharField(choices=[('PAYPAL', 'Paypal'), ('STRIPE', 'Stripe'), ('MPESA', 'Mpesa'), ('WORK', 'Work'), ('CHEQUE', 'Cheque')], default='MPESA', max_length=50)),
                ('amount', models.FloatField(blank=True, max_length=14, null=True)),
                ('trans_type', models.CharField(choices=[('DB', 'Debit'), ('CR', 'Credit')], default='CR', max_length=50, verbose_name='Type')),
                ('status', django_fsm.FSMField(default='pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('paypal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', django_fsm.FSMField(default='initiated', max_length=50, protected=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Initiate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True, unique=True)),
                ('MerchantRequestID', models.CharField(max_length=30, null=True, unique=True)),
                ('ResultCode', models.IntegerField(null=True)),
                ('mode', models.CharField(blank=True, max_length=40, null=True)),
                ('ResultDescription', models.TextField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiated Transaction',
                'verbose_name_plural': 'Initiated Transactions',
            },
        ),
        migrations.CreateModel(
            name='C2BPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=13)),
                ('TransID', models.CharField(max_length=50, unique=True)),
                ('TransTime', models.CharField(max_length=50)),
                ('TransAmount', models.FloatField()),
                ('BusinessShortCode', models.CharField(max_length=50)),
                ('BillRefNumber', models.CharField(max_length=50)),
                ('InvoiceNumber', models.CharField(max_length=50)),
                ('OrgAccountBalance', models.FloatField()),
                ('ThirdPartyTransID', models.CharField(max_length=50)),
                ('MSISDN', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('state', django_fsm.FSMField(default='initiated', max_length=50, protected=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer To Business Payments',
                'verbose_name_plural': 'Customer To Business Payment',
                'ordering': ['TransTime'],
            },
        ),
    ]
