# Generated by Django 3.2.14 on 2022-09-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220919_0038'),
        ('daraja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiate',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.order'),
        ),
    ]
