# Generated by Django 3.2.14 on 2022-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0003_alter_initiate_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=50, null=True, verbose_name='Reference No'),
        ),
    ]
