# Generated by Django 3.2.14 on 2022-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_videos_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='author_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
