# Generated by Django 3.2.14 on 2022-07-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_videos_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='author',
        ),
    ]
