# Generated by Django 3.2.14 on 2022-07-05 13:55

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_videos_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='videos', validators=[users.validators.file_size]),
        ),
    ]
