# Generated by Django 3.2.14 on 2022-09-16 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220916_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('495b9372-aef6-4f2a-b32b-4ad0cb5506ba'), primary_key=True, serialize=False),
        ),
    ]
