# Generated by Django 3.2.14 on 2022-09-18 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_plan_planid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-storage_size']},
        ),
        migrations.AddField(
            model_name='order',
            name='mode_of_payment',
            field=models.IntegerField(choices=[(0, 'PAYPAL'), (1, 'CHEQUE'), (2, 'MPESA')], default=1, verbose_name='Mode Of Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('642b5ab5-bf6a-4ae6-bf86-0765c608b51f'), primary_key=True, serialize=False),
        ),
    ]
