# Generated by Django 3.2.14 on 2022-09-18 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220918_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planentries',
            old_name='Plan',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='planentries',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='period',
            field=models.IntegerField(default=1, verbose_name='product ordered renewal period in months'),
        ),
        migrations.AddField(
            model_name='planentries',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='planentries',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.order'),
        ),
        migrations.AddField(
            model_name='planentries',
            name='period',
            field=models.IntegerField(default=1, verbose_name='product renewal period in months'),
        ),
        migrations.AddField(
            model_name='planentries',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.IntegerField(default=1, verbose_name='product renewal period in months'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('ab6176bc-5516-4bdf-a008-3a0c418953c5'), primary_key=True, serialize=False),
        ),
    ]
