# Generated by Django 3.2.14 on 2022-09-18 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220919_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('dc509e05-cef4-47cd-91e9-268950adae6e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
