# Generated by Django 3.2.14 on 2022-09-19 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220919_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='storage_size',
            field=models.FloatField(default=0, verbose_name='product storage size in GB'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('2bebae19-865c-4104-b011-d005f2b0e74b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_size',
            field=models.FloatField(default=0, verbose_name='product storage size in GB'),
        ),
    ]
