# Generated by Django 3.2.14 on 2022-09-19 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220919_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('5c12dc94-a47e-4d4e-80e5-528805c97e81'), editable=False, primary_key=True, serialize=False),
        ),
    ]
