# Generated by Django 3.2.14 on 2022-09-20 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_plan_planid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('aec17c51-50ad-456c-8484-dde92eac0869'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='storage_size',
            field=models.FloatField(default=0, verbose_name='product storage size in GB'),
        ),
    ]
