# Generated by Django 3.2.14 on 2022-09-21 11:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_plan_planid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('4160be2f-4986-4522-a8b1-83fd0743515c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
