# Generated by Django 3.2.14 on 2022-09-21 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220921_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('fe78e0c0-f6c8-4141-8700-1f49c63f7b94'), editable=False, primary_key=True, serialize=False),
        ),
    ]
