# Generated by Django 3.2.14 on 2022-09-21 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_plan_planid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.UUID('c769f0b3-80aa-4c17-99a8-19de7eb2147c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
