# Generated by Django 3.2.14 on 2022-09-21 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_plan_planid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planentries',
            options={'ordering': ['-entry_datetime']},
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
