# Generated by Django 3.2.14 on 2022-09-14 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSetup',
            fields=[
                ('ID', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_file_size', models.DecimalField(decimal_places=2, help_text='Maximum file size to be uploaded by a user in MB', max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('ID', models.UUIDField(default=uuid.UUID('a5dec95d-345f-4322-ba29-9512e7e66ab3'), primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('AUDIO', 'Audio')], default='VIDEO', max_length=50)),
                ('file', models.FileField(null=True, upload_to='files/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>')),
                ('file_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['file_name'],
            },
        ),
    ]
