# Generated by Django 3.2.14 on 2022-09-15 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('d7504dbc-5ff0-4734-b892-a4f5fc6a2a55'), primary_key=True, serialize=False),
        ),
    ]
