# Generated by Django 3.2.14 on 2022-09-16 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0002_alter_files_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesetup',
            name='max_file_size',
        ),
        migrations.AddField(
            model_name='filesetup',
            name='free_plan_restriction',
            field=models.IntegerField(choices=[(0, 'File Count'), (1, 'File Size'), (2, 'Both')], default=0, verbose_name='Free plan Restriction'),
        ),
        migrations.AddField(
            model_name='filesetup',
            name='max_no_of_free_files',
            field=models.IntegerField(default=0, verbose_name='Maximum No. of Files to Upload on Free Plan'),
        ),
        migrations.AddField(
            model_name='filesetup',
            name='max_of_free_file_size',
            field=models.FloatField(default=1, verbose_name='Maximum Size To upload On Free Plan in GB'),
        ),
        migrations.AddField(
            model_name='filesetup',
            name='subcribed_plan_restriction',
            field=models.IntegerField(choices=[(0, 'File Count'), (1, 'File Size'), (2, 'Both')], default=1, verbose_name='Subcribed plan Restriction'),
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('417869a0-8c60-48a0-90de-45fbd9b0fe10'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.CharField(choices=[(0, 'VIDEO'), (1, 'IMAGE'), (2, 'AUDIO')], default=0, max_length=50),
        ),
    ]
