# Generated by Django 3.2.14 on 2022-09-18 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0004_alter_files_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesetup',
            name='subcribed_plan_restriction',
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('5f488264-b382-48a2-94ac-964bb99f45e2'), primary_key=True, serialize=False),
        ),
    ]
