# Generated by Django 3.2.14 on 2022-09-18 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0006_auto_20220918_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('ID', models.UUIDField(default=uuid.UUID('2efa06f3-f2a7-41b0-90f5-ea31111f4e91'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('starting_no', models.CharField(max_length=50)),
                ('last_date_used', models.DateTimeField(auto_now_add=True)),
                ('last_no_used', models.CharField(max_length=50)),
                ('default_no', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('9732f4f6-4cf7-4c22-9899-26a7b3bd6d8a'), primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='filesetup',
            name='transaction_no_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filesManager.numberseries', verbose_name='Transactions No Series'),
        ),
    ]
