# Generated by Django 3.2.14 on 2022-09-18 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0008_auto_20220919_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('d20a0cd4-c9a8-4b4c-9527-6926c39eccbb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('7a42bac4-90b7-4edf-ac28-78032f65d92f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
