# Generated by Django 3.2.14 on 2022-09-19 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0009_auto_20220919_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberseries',
            name='starting_no',
        ),
        migrations.AddField(
            model_name='numberseries',
            name='prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='numberseries',
            name='suffix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('83eba1ea-08a0-457d-814b-8fe8b91dcdd3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('c598d965-cdab-4def-b998-740885e9e850'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='last_no_used',
            field=models.IntegerField(default=1, editable=False, verbose_name='Last Used Number'),
        ),
    ]
