# Generated by Django 3.2.14 on 2022-09-20 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0011_auto_20220919_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesetup',
            name='order_no_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_no_series', to='filesManager.numberseries', verbose_name='Order No Series'),
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('5828af5e-36d8-4def-abe8-a8eec62609be'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filesetup',
            name='transaction_no_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_no_series', to='filesManager.numberseries', verbose_name='Transactions No Series'),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('e02ab790-8546-4c1b-b133-756f9473ccc7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='last_no_used',
            field=models.IntegerField(default=0, editable=False, verbose_name='Last Used Number'),
        ),
    ]
