# Generated by Django 3.2.14 on 2022-09-21 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0013_auto_20220920_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('c10ec41e-01ca-4f88-aaa7-ecddb145f752'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('dcdfe99b-0ea7-46a1-9742-698cfd5e2470'), editable=False, primary_key=True, serialize=False),
        ),
    ]
