# Generated by Django 3.2.14 on 2022-09-21 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0014_auto_20220921_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberseries',
            name='number_of_fills',
            field=models.IntegerField(default=5, verbose_name='Number of Fillins'),
        ),
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('0e67ec40-04dc-4beb-bcfd-6dff6378fb55'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('9c6ee8e7-81d9-4fbd-946f-15fc4e902918'), editable=False, primary_key=True, serialize=False),
        ),
    ]
