# Generated by Django 3.2.14 on 2022-09-21 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0015_auto_20220921_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('3acadbac-ae4a-4f3f-aea9-0f5d967944a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
