# Generated by Django 3.2.14 on 2022-09-21 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesManager', '0016_auto_20220921_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberseries',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
